In [1]:
#RUN THIS CELL
#M
import requests
from IPython.core.display import HTML

# Import libraries
%matplotlib inline
import math
import numpy as np
import pandas as pd
#import seaborn as sns
from collections import Counter
import matplotlib.pyplot as plt
from sklearn.utils import shuffle
from sklearn.linear_model import Lasso
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_validate
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve
from sklearn.ensemble import RandomForestClassifier
#sns.set()

import warnings
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier

from sklearn import datasets,tree

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
#import seaborn as sns

from tqdm import tqdm
import time
from sklearn.model_selection import cross_val_score, train_test_split, GridSearchCV, KFold
from sklearn.metrics import accuracy_score, confusion_matrix, ConfusionMatrixDisplay, f1_score, roc_auc_score
from sklearn.metrics import recall_score, precision_score, classification_report, roc_curve
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.inspection import permutation_importance
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler
from sklearn.impute import SimpleImputer
#RUN THIS CELL 
import requests
from IPython.core.display import HTML

# Import libraries
%matplotlib inline
import math
import numpy as np
import pandas as pd
#import seaborn as sns
from collections import Counter
import matplotlib.pyplot as plt
from sklearn.utils import shuffle
from sklearn.linear_model import Lasso
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_validate
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve
#sns.set()

import warnings
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier

from sklearn import datasets,tree

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
#import seaborn as sns

from tqdm import tqdm
import time
from sklearn.model_selection import cross_val_score, train_test_split, GridSearchCV, KFold
from sklearn.metrics import accuracy_score, confusion_matrix, ConfusionMatrixDisplay, f1_score, roc_auc_score
from sklearn.metrics import recall_score, precision_score, classification_report, roc_curve
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.inspection import permutation_importance
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler
from sklearn.impute import SimpleImputer

from sklearn.decomposition import TruncatedSVD
from sklearn.datasets import load_svmlight_file
from sklearn.datasets import dump_svmlight_file
from scipy import sparse as sps
from sklearn.preprocessing import MinMaxScaler
from scipy.linalg import circulant
from sklearn.model_selection import train_test_split
from keras.optimizers import *
import random
import math
import pandas as pd
from tensorflow.python.keras.utils.data_utils import Sequence
import warnings
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
warnings.filterwarnings("ignore") 

import tensorflow.keras as k
import keras.backend as K
import numpy as np 
from keras.layers import *
from keras.models import Sequential, Model
from keras.regularizers import l2
import matplotlib.pyplot as plt
from keras.optimizers import Adam, Adadelta

from keras.callbacks import ModelCheckpoint, EarlyStopping


from tensorflow.python.framework.ops import disable_eager_execution
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report

disable_eager_execution()

%matplotlib inline
%matplotlib inline

In [2]:
import utils
import scipy
import sklearn
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

dictSize = 225
(X_raw, y_raw) = utils.loadData( "train", dictSize = dictSize )

In [3]:
X1=X_raw.toarray()
y1=y_raw 

from sklearn.decomposition import TruncatedSVD
svd = TruncatedSVD(n_components=224)
svd.fit(X1)
X_t = svd.transform(X1)
classes = np.unique(y1)
classes

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 34., 35., 37., 39., 40., 41., 42.,
       43., 44., 45., 46., 47., 48., 49., 50.])

In [4]:
# print (np.unique(y))
# unique, counts = np.unique(y, return_counts=True)
# print (unique)
# print (counts)

In [5]:
print(X_t.shape)
print(y1.shape)

(10000, 224)
(10000,)


In [6]:
X_train, X_test, y_train, y_test=train_test_split(X1,y1,test_size=0.2)

# sm = SMOTE()
# X_train_SMOTE, y_train_SMOTE = sm.fit_resample(X_train, y_train)


In [7]:
dt=DecisionTreeClassifier(class_weight="balanced")

In [8]:
dt.fit(X_train,y_train)

DecisionTreeClassifier(class_weight='balanced')

In [9]:
y_pred=dt.predict(X_test)

In [10]:
y_pred

array([ 3., 43.,  3., ...,  9.,  7.,  8.])

In [11]:
acc=accuracy_score(y_test, y_pred )

In [12]:
acc

0.688

In [13]:
# npzModel = np.load( "model.npz" )
# model = npzModel[npzModel.files[0]]
# 	# Let us predict a random subset of the 2k most popular labels no matter what the test point
# shortList = model[0:2*5]
# (i,j)=np.unique(model,return_index=True)
# print(shortList)
# print(model)
# print(i)
# print (j)

In [14]:
# a=np.array([4,3])
# b=np.array([[2,3, 6,22,2],[3,9,7,49,5]])
# utils.validateAndCleanup(a,b,5)

In [15]:
dict={'C':(0.001,0.01,0.1,1,10,100,1000) }#, 'solver':('newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga'),'multi_class':('auto', 'ovr','multinomial') } }

In [16]:
lr1=LogisticRegression()
clf=GridSearchCV(lr1, dict, scoring='accuracy')
clf.fit(X_train, y_train)


GridSearchCV(estimator=LogisticRegression(),
             param_grid={'C': (0.001, 0.01, 0.1, 1, 10, 100, 1000)},
             scoring='accuracy')

In [17]:
print( 'Best score: %0.3f' % clf.best_score_)
print( 'Best parameters set:')
best_parameters = clf.best_estimator_.get_params()
for param_name in sorted(dict.keys()):
    print( '\t%s: %r' % (param_name, best_parameters[param_name]) )

predictions = clf.predict(X_test)
print( classification_report(y_test, predictions) )
#print(accuracy_score(y_test, predictions))

Best score: 0.796
Best parameters set:
	C: 1000
              precision    recall  f1-score   support

         1.0       0.79      0.72      0.75       296
         2.0       0.90      0.95      0.92       508
         3.0       0.80      0.90      0.85       297
         4.0       0.72      0.80      0.76       306
         5.0       0.73      0.65      0.69        17
         6.0       0.50      1.00      0.67         2
         7.0       0.96      0.93      0.94        55
         8.0       0.91      0.81      0.86        53
         9.0       0.81      0.83      0.82        47
        10.0       0.74      0.76      0.75        45
        11.0       0.73      0.83      0.78        36
        12.0       0.00      0.00      0.00        37
        13.0       0.50      0.51      0.51        37
        14.0       0.00      0.00      0.00         2
        15.0       0.59      0.59      0.59        22
        16.0       0.54      0.30      0.39        23
        17.0       0.67      0.80

In [18]:
predic = clf.predict(X_test)
y_pred = clf.best_estimator_.predict(X_test)
predic3 = clf.best_estimator_

print(predic)
print(y_pred)
print(predic3)
#print(accuracy_score(y_test,y_pred))

[2. 4. 3. ... 9. 7. 8.]
[2. 4. 3. ... 9. 7. 8.]
LogisticRegression(C=1000)


In [19]:
from sklearn.decomposition import TruncatedSVD
from sklearn.svm import SVC
from sklearn.cluster import KMeans

#svd = TruncatedSVD(n_components=224)
#svd.fit(X1)
#X_t = svd.transform(X1)
X_train, X_test, y_train, y_test=train_test_split(X_t,y1,test_size=0.2)

#kms  = KMeans()
#kms.fit(X_train)

#y_train = kms.labels_
#print(y_train)
#y_test = kms.predict(X_test)

lr=LogisticRegression(class_weight="balanced", solver='liblinear')
lr.fit(X_train, y_train)
#y_pred=lr.predict(X_test)
acc2=accuracy_score(y_test,y_pred)
proba=lr.predict_proba(X_test)
ind = np.argsort(proba)[:,-1:-6:-1]

print (acc2)
print (ind.shape)
yPred = lr.classes_[ind]

0.1425
(2000, 5)


In [20]:
preck = utils.getPrecAtK( y_test, yPred, 5 )
# The macro precision code takes a bit longer to execute due to the for loop over labels
mpreck = utils.getMPrecAtK( y_test,yPred, 5 )

# According to our definitions, both prec@k and mprec@k should go up as k goes up i.e. for your
# method, prec@i > prec@j if i > j and mprec@i > mprec@j if i > j. See the assignment description
# to convince yourself why this must be the case.

print( "prec@1: %0.3f" % preck[0], "prec@3: %0.3f" % preck[2], "prec@5: %0.3f" % preck[4] )
# Dont be surprised if mprec is small -- it is hard to do well on rare error classes
print( "mprec@1: %0.3e" % mpreck[0], "mprec@3: %0.3e" % mpreck[2], "mprec@5: %0.3e" % mpreck[4] )

prec@1: 0.720 prec@3: 0.887 prec@5: 0.933
mprec@1: 7.078e-01 mprec@3: 8.894e-01 mprec@5: 9.304e-01


In [21]:
print(accuracy_score(y_test, y_pred))

0.1425


In [22]:
from sklearn.decomposition import TruncatedSVD
from sklearn.svm import SVC
from sklearn.cluster import KMeans

#svd = TruncatedSVD(n_components=224)
#svd.fit(X1)
#X_t = svd.transform(X1)
X_train, X_test, y_train, y_test=train_test_split(X_t,y1,test_size=0.2)

#kms  = KMeans()
#kms.fit(X_train)

#y_train = kms.labels_
#print(y_train)
#y_test = kms.predict(X_test)

lr=LogisticRegression(class_weight="balanced", solver='liblinear')
lr.fit(X_train, y_train)
y_pred2=lr.predict(X_test)
acc2=accuracy_score(y_test,y_pred2)
proba=lr.predict_proba(X_test)
ind = np.argsort(proba)[:,-1:-6:-1]

print (acc2)
print (ind.shape)
yPred = lr.classes_[ind]

0.735
(2000, 5)


In [23]:
X_train.shape

(8000, 224)

In [24]:
y_train.shape

(8000,)

In [25]:
preck = utils.getPrecAtK( y_test, yPred, 5 )
# The macro precision code takes a bit longer to execute due to the for loop over labels
mpreck = utils.getMPrecAtK( y_test,yPred, 5 )

# According to our definitions, both prec@k and mprec@k should go up as k goes up i.e. for your
# method, prec@i > prec@j if i > j and mprec@i > mprec@j if i > j. See the assignment description
# to convince yourself why this must be the case.

print( "prec@1: %0.3f" % preck[0], "prec@3: %0.3f" % preck[2], "prec@5: %0.3f" % preck[4] )
# Dont be surprised if mprec is small -- it is hard to do well on rare error classes
print( "mprec@1: %0.3e" % mpreck[0], "mprec@3: %0.3e" % mpreck[2], "mprec@5: %0.3e" % mpreck[4] )

prec@1: 0.735 prec@3: 0.904 prec@5: 0.945
mprec@1: 6.459e-01 mprec@3: 8.579e-01 mprec@5: 8.979e-01


In [26]:
#plt.plot('proba', label = 'accuracy')
#plt.grid(True)
#plt.legend()