In [8]:
#RUN THIS CELL 
import requests
from IPython.core.display import HTML

# Import libraries
%matplotlib inline
import math
import numpy as np
import pandas as pd
#import seaborn as sns
from collections import Counter
import matplotlib.pyplot as plt
from sklearn.utils import shuffle
from sklearn.linear_model import Lasso
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_validate
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve
#sns.set()

import warnings
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier

from sklearn import datasets,tree

#from tqdm import tqdm
import time
from sklearn.model_selection import cross_val_score, train_test_split, GridSearchCV, KFold
from sklearn.metrics import accuracy_score, confusion_matrix, ConfusionMatrixDisplay, f1_score, roc_auc_score
from sklearn.metrics import recall_score, precision_score, classification_report, roc_curve
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.inspection import permutation_importance
#from imblearn.over_sampling import SMOTE
#from imblearn.under_sampling import RandomUnderSampler
from sklearn.impute import SimpleImputer
%matplotlib inline

In [9]:
import utils
import scipy
import sklearn
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

dictSize = 225
(X_raw, y_raw) = utils.loadData( "train", dictSize = dictSize )

In [10]:
X1=X_raw.toarray()
y1=y_raw 

In [11]:
# print (np.unique(y))
# unique, counts = np.unique(y, return_counts=True)
# print (unique)
# print (counts)

In [12]:
print(X1.shape)
print(y1.shape)

(10000, 225)
(10000,)


In [13]:
X_train, X_test, y_train, y_test=train_test_split(X1,y1,test_size=0.2)

# sm = SMOTE()
# X_train_SMOTE, y_train_SMOTE = sm.fit_resample(X_train, y_train)


In [14]:
rf=RandomForestClassifier(class_weight="balanced")

In [15]:
rf.fit(X_train,y_train)

RandomForestClassifier(class_weight='balanced')

In [16]:
y_pred=rf.predict(X_test)

In [17]:
y_pred

array([ 4., 30.,  4., ..., 13.,  7.,  8.])

In [18]:
proba2=rf.predict_proba(X_test)

In [19]:
ind2 = np.argsort(proba2)[:,-1:-6:-1]

In [20]:
yPred2 = rf.classes_[ind2]

In [21]:
preck = utils.getPrecAtK( y_test, yPred2, 5 )
# The macro precision code takes a bit longer to execute due to the for loop over labels
mpreck = utils.getMPrecAtK( y_test,yPred2, 5 )

# According to our definitions, both prec@k and mprec@k should go up as k goes up i.e. for your
# method, prec@i > prec@j if i > j and mprec@i > mprec@j if i > j. See the assignment description
# to convince yourself why this must be the case.

print( "prec@1: %0.3f" % preck[0], "prec@3: %0.3f" % preck[2], "prec@5: %0.3f" % preck[4] )
# Dont be surprised if mprec is small -- it is hard to do well on rare error classes
print( "mprec@1: %0.3e" % mpreck[0], "mprec@3: %0.3e" % mpreck[2], "mprec@5: %0.3e" % mpreck[4] )

prec@1: 0.744 prec@3: 0.907 prec@5: 0.957
mprec@1: 5.808e-01 mprec@3: 7.470e-01 mprec@5: 8.161e-01


In [22]:
acc=accuracy_score(y_test, y_pred )

In [23]:
acc

0.744

In [24]:
# npzModel = np.load( "model.npz" )
# model = npzModel[npzModel.files[0]]
# 	# Let us predict a random subset of the 2k most popular labels no matter what the test point
# shortList = model[0:2*5]
# (i,j)=np.unique(model,return_index=True)
# print(shortList)
# print(model)
# print(i)
# print (j)

In [25]:
# a=np.array([4,3])
# b=np.array([[2,3, 6,22,2],[3,9,7,49,5]])
# utils.validateAndCleanup(a,b,5)

In [26]:
lr=LogisticRegression(max_iter=1000)

lr.fit(X_train, y_train)
y_pred2=lr.predict(X_test)
acc2=accuracy_score(y_test,y_pred2)
proba=lr.predict_proba(X_test)

In [27]:
ind = np.argsort(proba)[:,-1:-6:-1]

In [28]:
print (acc2)
print (ind.shape)

0.804
(2000, 5)


In [29]:
# a=proba[0,:].sum()
# print(a)
# print (proba.shape)

In [30]:
yPred = lr.classes_[ind]

In [31]:
preck = utils.getPrecAtK( y_test, yPred, 5 )
# The macro precision code takes a bit longer to execute due to the for loop over labels
mpreck = utils.getMPrecAtK( y_test,yPred, 5 )

# According to our definitions, both prec@k and mprec@k should go up as k goes up i.e. for your
# method, prec@i > prec@j if i > j and mprec@i > mprec@j if i > j. See the assignment description
# to convince yourself why this must be the case.

print( "prec@1: %0.3f" % preck[0], "prec@3: %0.3f" % preck[2], "prec@5: %0.3f" % preck[4] )
# Dont be surprised if mprec is small -- it is hard to do well on rare error classes
print( "mprec@1: %0.3e" % mpreck[0], "mprec@3: %0.3e" % mpreck[2], "mprec@5: %0.3e" % mpreck[4] )

prec@1: 0.804 prec@3: 0.930 prec@5: 0.964
mprec@1: 5.376e-01 mprec@3: 7.528e-01 mprec@5: 8.448e-01


In [32]:
params=np.zeros((50, 225))
for i in range (50):
	temp=X_train[y_train==i+1]
	if temp.shape[0]!=0:
		temp2=temp.sum(axis=0)/temp.shape[0]
		params[i,:]=temp2[np.newaxis,:]

In [33]:
params.shape

(50, 225)

In [34]:
X_test.shape

(2000, 225)

In [35]:
X_test_temp=X_test.reshape(X_test.shape[0],1,-1)

In [36]:
X_test_temp.shape

(2000, 1, 225)

In [37]:
delta=params-X_test_temp

In [38]:
delta.shape

(2000, 50, 225)

In [39]:
squared_deltas = np.square(delta)

# Sum along the row elements i.e. Vertical summation
squared_deltas_sum = squared_deltas.sum(axis=2)

# Calculate the square root of squared_deltas_sum
distances = np.sqrt(squared_deltas_sum)

In [40]:
distances.shape

(2000, 50)

In [41]:
distances

array([[2.61590465, 2.73194483, 3.40294864, ..., 3.3936922 , 3.84960315,
        3.54115693],
       [3.16687311, 2.65407918, 2.78364051, ..., 3.44245263, 3.64958141,
        2.61417483],
       [2.19307878, 2.18177946, 2.94717569, ..., 2.74174156, 3.69496655,
        3.15460887],
       ...,
       [4.35347017, 4.0965938 , 3.97074757, ..., 3.85843455, 4.58106004,
        4.10291482],
       [4.2063884 , 3.98606998, 3.68242104, ..., 4.15426137, 3.58042518,
        3.85148154],
       [9.3979958 , 9.07139007, 8.82510843, ..., 9.11239076, 9.43324499,
        9.10777454]])

In [42]:
index = np.argsort(distances, axis=1)[:,:5]

In [43]:
index

array([[17,  0,  1, 36, 21],
       [43, 42, 23, 11, 40],
       [36, 17,  1,  0, 34],
       ...,
       [29, 12, 46, 22,  4],
       [ 6, 25,  3, 48,  9],
       [33, 20, 10, 39, 30]], dtype=int64)

In [44]:
yPred3=index+1

In [45]:
preck = utils.getPrecAtK( y_test, yPred3, 5 )
# The macro precision code takes a bit longer to execute due to the for loop over labels
mpreck = utils.getMPrecAtK( y_test,yPred3, 5 )

# According to our definitions, both prec@k and mprec@k should go up as k goes up i.e. for your
# method, prec@i > prec@j if i > j and mprec@i > mprec@j if i > j. See the assignment description
# to convince yourself why this must be the case.

print( "prec@1: %0.3f" % preck[0], "prec@3: %0.3f" % preck[2], "prec@5: %0.3f" % preck[4] )
# Dont be surprised if mprec is small -- it is hard to do well on rare error classes
print( "mprec@1: %0.3e" % mpreck[0], "mprec@3: %0.3e" % mpreck[2], "mprec@5: %0.3e" % mpreck[4] )

prec@1: 0.239 prec@3: 0.473 prec@5: 0.578
mprec@1: 3.878e-01 mprec@3: 5.347e-01 mprec@5: 6.338e-01
