In [29]:
from keras.models import load_model
model = load_model('Model.h5')

In [30]:
from pyzbar.pyzbar import decode

In [31]:
# import matplotlib.pyplot as plt
import numpy as np
# import pandas as pd 
import matplotlib.pyplot as plt
import tensorflow as tf
# from tensorflow.keras import layers
from time import perf_counter 
import os
import cv2
import pywhatkit
import csv
# from tensorflow.keras.preprocessing.image import ImageDataGenerator
# from tensorflow.keras.models import Sequential
# from keras.utils.vis_utils import plot_model
from tensorflow.keras.preprocessing import image
# import datetime
from time import gmtime, strftime
# # import easyocr
# # import imutils

In [32]:
#from IPython.display import Video

In [33]:
# x=strftime("%H %M")
# x = [int(i) for i in x.split()]   
# x 

In [34]:
# ## Defining batch specfications
batch_size = 16
img_height = 360
img_width = 480

In [35]:
# train_ds = tf.keras.preprocessing.image_dataset_from_directory(
#     'train',
#     seed=40,
#     image_size= (img_height, img_width),
#     batch_size=batch_size

# )

In [36]:
testing_ds = tf.keras.preprocessing.image_dataset_from_directory(
    'D:/MLModel/our_dataset_big/test',
    seed=40,
    image_size= (img_height, img_width),
    batch_size=batch_size)

class_names = testing_ds.class_names
print(class_names)
 
# for image_batch, labels_batch in train_ds:
#   print(image_batch.shape)
#   print(labels_batch.shape)
#   break

Found 664 files belonging to 2 classes.
['class1', 'class2']


In [37]:
# val_ds = tf.keras.preprocessing.image_dataset_from_directory(
#     'val',
#     seed=40,
#     image_size= (img_height, img_width),
#     batch_size=batch_size) 

In [38]:
# for images, labels in testing_ds.take(1):
#     for i in range(1):
#         img = images[i].numpy().astype("uint8")
#         plt.imshow(img)
#         plt.title(class_names[labels[i]])

In [39]:
# def numplatedect(img):
#     print("Got it")
#     plt.imshow(img)
#     gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
#     #plt.imshow(cv2.cvtColor(gray, cv2.COLOR_BGR2RGB))
#     bfilter = cv2.bilateralFilter(gray, 11, 17, 17) #Noise reduction
#     edged = cv2.Canny(bfilter, 30, 200) #Edge detection
#     #plt.imshow(cv2.cvtColor(edged, cv2.COLOR_BGR2RGB))
#     keypoints = cv2.findContours(edged.copy(), cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
#     contours = imutils.grab_contours(keypoints)
#     contours = sorted(contours, key=cv2.contourArea, reverse=True)[:10]

#     # contours

#     location = None
#     for contour in contours:
#         approx = cv2.approxPolyDP(contour, 10, True,)
    
#         if len(approx) == 4:
#             location = approx
#             break
#     location    
#     mask = np.zeros(gray.shape, np.uint8)
#     new_image = cv2.drawContours(mask, [location], 0,255, -1)
#     new_image = cv2.bitwise_and(img, img, mask=mask)
#     #plt.imshow(cv2.cvtColor(new_image, cv2.COLOR_BGR2RGB))
#     (x,y) = np.where(mask==255)
#     (x1, y1) = (np.min(x), np.min(y))
#     (x2, y2) = (np.max(x), np.max(y))
#     cropped_image = gray[x1:x2+1, y1:y2+1]
#     #plt.imshow(cropped_image)
#     reader = easyocr.Reader(['en'])
#     result = reader.readtext(cropped_image)
#     result
#     text = result[0][-2]
#     text
    
    

In [40]:
# plt.figure(figsize=(8, 8))
# for images, labels in train_ds.take(1):
#   for i in range(6):
#     ax = plt.subplot(3, 3, i+1)
#     plt.imshow(images[i].numpy().astype("uint8"))
#     plt.title(class_names[labels[i]])
#     plt.axis("off")

In [41]:
# # MAIN
# #Original and perfect
# # My camera fps is 30. 
# #path = 'D:\Y'
# plt.figure(figsize=(15, 15))
# for images, labels in testing_ds.take(1):
#         for i in range(10):
#             img = images[i].numpy().astype("uint8")
#             # img_array = tf.keras.utils.img_to_array(img)
#             # img_array = tf.expand_dims(img_array, 0) # Create a batch
#             # predictions = model.predict(img_array)
#             # score = tf.nn.softmax(predictions)
            
#             # ax = plt.subplot(5, 5, i+1)
#             # plt.imshow(images[i].numpy().astype("uint8"))
#             # plt.title([i])
#             # plt.axis("off")

#             # print(
#             #     "{} image most likely belongs to {} with a {:.2f} percent confidence."
#             #     .format(i, class_names[np.argmax(score)], 100 * np.max(score))
#             #     )
            

#             Y = image.img_to_array(img)
#             X = np.expand_dims(Y,axis=0)
#             val = model.predict(X)
#             print(val)

            
# #             print(score)
#             if val[0][1] > 0.5:
#                 cv2.imwrite(os.path.join('D:\Y\test' , 'NA{:d}.jpg'.format(i)), img)
#             else:
#                 cv2.imwrite(os.path.join('D:\Y\test' , 'A{:d}.jpg'.format(i)), img)
# #                 #numplatedect(img)

In [42]:
# img = tf.keras.utils.load_img(
#     'copy_path', target_size=(img_height, img_width)
# )
# img_array = tf.keras.utils.img_to_array(img)
# img_array = tf.expand_dims(img_array, 0) # Create a batch

# predictions = Model.predict(img_array)
# score = tf.nn.softmax(predictions[0])

# print(
#     "This image most likely belongs to {} with a {:.2f} percent confidence."
#     .format(class_names[np.argmax(score)], 100 * np.max(score)))

In [43]:
# vidcap = cv2.VideoCapture('test.mp4')
# success,image = vidcap.read()
# path = 'D:/Y/test' #fuck this error # Use / instead of \..... fuck it!!!
# while success:
#     cv2.imwrite(os.path.join(path, "frame%d.jpg" % count ), image)     # save frame as JPEG file      
#     success,image = vidcap.read()
#     print('Read a new frame: ', success)
#     count += 1

In [44]:
# testing_ds = tf.keras.preprocessing.image_dataset_from_directory(
#     'vid_test',
#     seed=40,
#     image_size= (img_height, img_width),
#     batch_size=batch_size)
# # class_names = testing_ds.class_names
# # print(class_names)
# #plt.imshow(train)

In [45]:
# ## lets vizualize results on testing data
# AccuracyVector = []
# plt.figure(figsize=(15, 15))
# for images, labels in testing_ds.take(1):
#     predictions = model.predict(images)
#     predlabel = []
#     prdlbl = []
    
    
#     for mem in predictions:
# #        mem = tf.nn.softmax(predictions[0])
#         predlabel.append(class_names[np.argmax(mem)])
#         prdlbl.append(np.argmax(mem))
    
#     AccuracyVector = np.array(prdlbl) == labels
#     for i in range(9):
#         ax = plt.subplot(3, 3, i + 1)
#         plt.imshow(images[i].numpy().astype("uint8"))
#         plt.title('Pred: '+ predlabel[i]+' actl:'+class_names[labels[i]])
#         plt.axis("off")
# print(predictions)

In [46]:
# ##After above code in camera file
# #Original and perfect
# # My camera fps is 30. 
# #path = 'D:\Y'
# plt.figure(figsize=(15, 15))
# for images, labels in testing_ds.take(1):
#         for i in range(10):
            
#             img = images[i].numpy().astype("uint8")
#             img_array = tf.keras.utils.img_to_array(img)
#             img_array = tf.expand_dims(img_array, 0) # Create a batch
#             predictions = model.predict(img_array)
#             score = tf.nn.softmax(predictions)
            
#             ax = plt.subplot(5, 5, i+1)
#             plt.imshow(images[i].numpy().astype("uint8"))
#             plt.title([i])
#             plt.axis("off")
# #             Y = image.img_to_array(img)
# #             X = np.expand_dims(Y,axis=0)
# #            val = model.predict(X)

#             print(
#                 "{} image most likely belongs to {} with a {:.2f} percent confidence."
#                 .format(i, class_names[np.argmax(score)], 100 * np.max(score)))
            
# #             print(score)
# #             if val[0][1] > 0.5:
# #                 cv2.imwrite(os.path.join('D:\Y\Accident-No' , 'NA{:d}.jpg'.format(i)), img)
# #             else:
# #                 cv2.imwrite(os.path.join('D:\Y\Accident-Yes' , 'A{:d}.jpg'.format(i)), img)
# #                 #numplatedect(img)

In [47]:

#cap=cv2.VideoCapture(1)

In [48]:
#Original
# My camera fps is 30. 
import cv2
import os
import time

cam = cv2.VideoCapture(0)
# path = 'D:\Y\Accident-No'
# path2 = 'D:\Y\Accident-Yes'

last_recorded_time = time.time()# this keeps track of the last time a frame was processed
count=0
plt.figure(figsize=(15, 15))

# i=0 #increasing count after every loop
# j=0 # counting 3 second after accident occurs
k=[] #for storing value of barcode if accident occuers
# m=1 #if loop goes inside the accident then it doesnt go back insaide the accident before verification

while count <30:
#     i+=1
    #x=strftime("%d-%m-%Y %z")# ':' not allowed in file name
    curr_time = time.time() # grab the current time
    # keep these three statements outside of the if statement, so we 
    # can still display the camera/video feed in real time
    suc, frame = cam.read()
    frame = cv2.resize(frame,(200,200),fx=0,fy=0, interpolation = cv2.INTER_CUBIC)
    #plt.imshow(frame)
    #frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    
    #operation like 'imshow' on image
    cv2.imshow('image', frame)
    
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
    
    
    if curr_time - last_recorded_time >= 1:# it has been at least 5 seconds
        count+=1
        Y = image.img_to_array(frame)
        X = tf.expand_dims(Y,axis=0)
        val = model.predict(X)
        print(val)        

#         img = images[i].numpy().astype("uint8")
#         img_array = tf.keras.utils.img_to_array(frame)
#         img_array = tf.expand_dims(img_array, 0) # Create a batch
#         predictions = model.predict(img_array)
#         score = tf.nn.softmax(predictions[0])
        
#         x = class_names[np.argmax(score)]
            
#         ax = plt.subplot(5, 5, i+1)
#         plt.imshow(images[i].numpy().astype("uint8"))
#         plt.title([i])
#         plt.axis("off")
        
        
        if val[0][1] > 0.5:
            print("Non-Acc")
        #if predictions[0][1] > 0.5:
#            cv2.imwrite(os.path.join('D:\Y\Accident-No' , F"{count}.jpg"), frame)
        if(val[0][1]<=0.5):
            for i in range (10):
                suce, frame = cam.read()
                #cv2.imshow('img',frame1)
                print(decode(frame))
                for barcode in decode(frame):
                    print('lellu')
                    my_data=barcode.data.decode('utf-8')
                    pts=np.array([barcode.polygon],np.int32)
                    pts=pts.reshape((-1,1,2))
                    cv2.polylines(frame,[pts],True,(255,0,255),5)
                    pts2=barcode.rect
                    cv2.putText(frame,my_data,(pts2[0],pts2[1]),cv2.FONT_HERSHEY_PLAIN,0.9,(255,0,255),2)
                    if(my_data):
                        k.append(my_data)
                    cv2.waitKey(1000)
            
            for i in range (10):
                suce, frame = cam.read()
                #cv2.imshow('img',frame1)
                for barcode in decode(frame):
                    print('pellu')
                    my_data=barcode.data.decode('utf-8')
                    pts=np.array([barcode.polygon],np.int32)
                    pts=pts.reshape((-1,1,2))
                    cv2.polylines(frame,[pts],True,(255,0,255),5)
                    pts2=barcode.rect
                    cv2.putText(frame,my_data,(pts2[0],pts2[1]),cv2.FONT_HERSHEY_PLAIN,0.9,(255,0,255),2)
                    if (my_data in k):
                        print('leliya')

                    append_data=[
                         [my_data,'0']
                                ]
                    cv2.imwrite(os.path.join('D:\Y\Accident-Yes' , F"{count}.jpg" ), frame)
                    file=open('car_names.csv','a',newline='')
                    writer=csv.writer(file)
                    writer.writerows(append_data)
                    file.close()
                    x=strftime("%H %M")
                    x = [int(i) for i in x.split()]  
                    pywhatkit.sendwhatmsg('+919553652018', 'Message 1', x[0],x[1]+1.2 )
                    break

        last_recorded_time = curr_time
        
cam.release()
cv2.destroyAllWindows()

1/1 [==============================] - 0s 493ms/step
[[0.6135771 0.3864229]]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
1/1 [==============================] - 0s 148ms/step
[[0.51067275 0.48932722]]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
1/1 [==============================] - 0s 109ms/step
[[0.65634996 0.34365   ]]
[]
[]
[Decoded(data=b'HU1414', type='QRCODE', rect=Rect(left=399, top=209, width=61, height=62), polygon=[Point(x=399, y=259), Point(x=450, y=271), Point(x=460, y=220), Point(x=409, y=209)], quality=1, orientation='LEFT')]
lellu
[Decoded(data=b'HU1414', type='QRCODE', rect=Rect(left=370, top=187, width=62, height=62), polygon=[Point(x=370, y=236), Point(x=419, y=249), Point(x=432, y=200), Point(x=381, y=187)], quality=1, orientation='LEFT')]
lellu
[]
[]
[]
[Decoded(data=b'HU1414', type='QRCODE', rect=Rect(left=359, top=172, width=62, height=63), polygon=[Point(x=359, y=223), Point(x=409, y=235), Point(x=421, y=185), Point(x=371, y=172)], quality=1, orientation='LEFT')]
lellu
[]
[]
pellu
leliya
In

<Figure size 1500x1500 with 0 Axes>

In [50]:
# syntax: phone number with country code, message, hour and minutes
#pywhatkit.sendwhatmsg('+919553652018', 'Message 1', x[0],x[1] )

In [53]:
# #Original
# # My camera fps is 30. 
# import cv2
# import os
# import time

# # path = 'D:\Y\Accident-No'
# # path2 = 'D:\Y\Accident-Yes'

# last_recorded_time = time.time()# this keeps track of the last time a frame was processed
# count =0
# plt.figure(figsize=(15, 15))

# # i=0 #increasing count after every loop
# # j=0 # counting 3 second after accident occurs
# k=[] #for storing value of barcode if accident occuers
# # m=1 #if loop goes inside the accident then it doesnt go back insaide the accident before verification

# while count <20:
# #     i+=1
#     #x=strftime("%d-%m-%Y %z")# ':' not allowed in file name
#     curr_time = time.time() # grab the current time
#     # keep these three statements outside of the if statement, so we 
#     # can still display the camera/video feed in real time
#     suc, frame = cam.read()
#     frame = cv2.resize(frame,(200,200),fx=0,fy=0, interpolation = cv2.INTER_CUBIC)
#     #plt.imshow(frame)
#     #frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    
#     #operation like 'imshow' on image
#     cv2.imshow('image', frame)
    
#     if cv2.waitKey(1) & 0xFF == ord('q'):
#         break
    
    
#     if curr_time - last_recorded_time >= 2:# it has been at least 5 seconds
# #        count+=1
#         Y = image.img_to_array(frame)
#         X = tf.expand_dims(Y,axis=0)
#         val = model.predict(X)
#         print(val)        

# #         img = images[i].numpy().astype("uint8")
# #         img_array = tf.keras.utils.img_to_array(frame)
# #         img_array = tf.expand_dims(img_array, 0) # Create a batch
# #         predictions = model.predict(img_array)
# #         score = tf.nn.softmax(predictions[0])
        
# #         x = class_names[np.argmax(score)]
            
# #         ax = plt.subplot(5, 5, i+1)
# #         plt.imshow(images[i].numpy().astype("uint8"))
# #         plt.title([i])
# #         plt.axis("off")
        
        
#         if val[0][1] > 0.5:
#             print("Non-Acc")
#         #if predictions[0][1] > 0.5:
# #            cv2.imwrite(os.path.join('D:\Y\Accident-No' , F"{count}.jpg"), frame)
#         if(val[0][1]<=0.5):
#             for i in range (10):
#                 suce, frame1 = cap.read()
#                 cv2.imshow('img',frame1)
#                 print(decode(frame))
#                 for barcode in decode(frame):
#                     print('lellu')
#                     my_data=barcode.data.decode('utf-8')
#                     pts=np.array([barcode.polygon],np.int32)
#                     pts=pts.reshape((-1,1,2))
#                     cv2.polylines(frame,[pts],True,(255,0,255),5)
#                     pts2=barcode.rect
#                     cv2.putText(frame,my_data,(pts2[0],pts2[1]),cv2.FONT_HERSHEY_PLAIN,0.9,(255,0,255),2)
#                     if(my_data):
#                         k.append(my_data)
#                     cv2.waitKey(2000)
            
#             for i in range (10):
#                 suce, frame1 = cap.read()
#                 cv2.imshow('img',frame1)
#                 for barcode in decode(frame):
#                     print('pellu')
#                     my_data=barcode.data.decode('utf-8')
#                     pts=np.array([barcode.polygon],np.int32)
#                     pts=pts.reshape((-1,1,2))
#                     cv2.polylines(frame,[pts],True,(255,0,255),5)
#                     pts2=barcode.rect
#                     cv2.putText(frame,my_data,(pts2[0],pts2[1]),cv2.FONT_HERSHEY_PLAIN,0.9,(255,0,255),2)
#                     if (my_data in k):
#                         print('leliya')

#                     append_data=[
#                          [my_data,'0']
#                                 ]
#                     cv2.imwrite(os.path.join('D:\Y\Accident-Yes' , F"{count}.jpg" ), frame)
#                     file=open('car_names.csv','a',newline='')
#                     writer=csv.writer(file)
#                     writer.writerows(append_data)
#                     file.close()
        
            
            
        
        
        
        
        
# #             print("Acc")
# #             #cv2.imwrite(os.path.join('D:\Y\Accident-Yes' , F"{count}.jpg"), frame)
# # #            i = count
# #             print(decode(frame))
# #             for barcode in decode(frame):
# #                 print("sd")
# #                 my_data=barcode.data.decode('utf-8')
# #                 pts=np.array([barcode.polygon],np.int32)
# #                 pts=pts.reshape((-1,1,2))
# #                 cv2.polylines(frame,[pts],True,(255,0,255),5)
# #                 pts2=barcode.rect
# #                 cv2.putText(frame,my_data,(pts2[0],pts2[1]),cv2.FONT_HERSHEY_PLAIN,0.9,(255,0,255),2)
# #                 if(my_data):
# #                     k.append(my_data)
# #                     j=i
# #                     m=0
            
            
# #         if(j):
# #             print('jellu')
# #             j=j+1
# #         if(i==j+2):
# #             for barcode in decode(frame):
# #                 print('lellu')
# #                 my_data=barcode.data.decode('utf-8')
# #                 pts=np.array([barcode.polygon],np.int32)
# #                 pts=pts.reshape((-1,1,2))
# #                 cv2.polylines(frame,[pts],True,(255,0,255),5)
# #                 pts2=barcode.rect
# #                 cv2.putText(frame,my_data,(pts2[0],pts2[1]),cv2.FONT_HERSHEY_PLAIN,0.9,(255,0,255),2)
# #                 if (my_data in k):
# #                     print('leliya')
                                                       
# #                     append_data=[
# #                          [my_data,'0']
# #                                 ]
# #                     cv2.imwrite(os.path.join('D:\Y\Accident-Yes' , F"{count}.jpg" ), frame)
# #                     file=open('car_names.csv','a',newline='')
# #                     writer=csv.writer(file)
# #                     writer.writerows(append_data)
# #                     file.close()
# #             j=0
# #             k=[]
# #             m=1
        
              
             
#         #frame = frame.reshape(-1, 200, 200 ,3)
#         #print (frame.shape)
#         #frame = cv2.resize(frame,(200,200))
#         #plt.imshow(img)
#         #Y = image.img_to_array(frame)
            
#         #PROCESS YOUR IMAGE VARIABLE, img
#         #cv2.imwrite(os.path.join(path , 'frame{:d}.jpg'.format(count) ), frame)
#         #IMPORTANT CODE BELOW
#         last_recorded_time = curr_time
        
# cam.release()
# cv2.destroyAllWindows()

1/1 [==============================] - 0s 57ms/step
[[0.9582128  0.04178714]]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
1/1 [==============================] - 0s 61ms/step
[[0.68876153 0.31123847]]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
1/1 [==============================] - 0s 50ms/step
[[0.49877828 0.5012217 ]]
Non-Acc
1/1 [==============================] - 0s 54ms/step
[[0.5776402  0.42235982]]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
1/1 [==============================] - 0s 55ms/step
[[0.5435487 0.4564513]]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
1/1 [==============================] - 0s 78ms/step
[[0.11918475 0.88081527]]
Non-Acc
1/1 [==============================] - 0s 56ms/step
[[0.6099762 0.3900239]]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
1/1 [==============================] - 0s 56ms/step
[[0.75735    0.24264999]]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
1/1 [==============================] - 0s 50ms/step
[[0.727184   0.27281597]]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
1/1 [==============================] - 0s 56ms/step
[[0.81502175 0.18497823]

[]
[]
[]
[]
1/1 [==============================] - 0s 54ms/step
[[0.77115905 0.22884098]]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
1/1 [==============================] - 0s 54ms/step
[[0.73122746 0.26877254]]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
1/1 [==============================] - 0s 55ms/step
[[0.7363621  0.26363793]]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
1/1 [==============================] - 0s 54ms/step
[[0.6508474  0.34915265]]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
1/1 [==============================] - 0s 53ms/step
[[0.5499946  0.45000538]]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
1/1 [==============================] - 0s 81ms/step
[[0.48613602 0.5138639 ]]
Non-Acc
1/1 [==============================] - 0s 54ms/step
[[0.6929741  0.30702594]]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
1/1 [==============================] - 0s 58ms/step
[[0.6831157  0.31688422]]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
1/1 [==============================] - 0s 54ms/step
[[0.6891704  0.31082958]]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
1/1 [==============================] -

<Figure size 1500x1500 with 0 Axes>

In [55]:
cap.release()

In [8]:
class_names = ['Accident', 'Non Accident']

In [61]:
# #Original
# # My camera fps is 30. 
# import cv2
# import os
# import time
# #arr =[]
# # path = 'D:\Y\Accident-No'
# # path2 = 'D:\Y\Accident-Yes'
# cam=cv2.VideoCapture(0)
# # cam.set(3, 480)
# # cam.set(4, 360)
# last_recorded_time = time.time()# this keeps track of the last time a frame was processed
# count =0
# plt.figure(figsize=(15, 15))

# while count <20:
#     #x=strftime("%d-%m-%Y %z")# ':' not allowed in file name
#     curr_time = time.time() # grab the current time
#     # keep these three statements outside of the if statement, so we 
#     # can still display the camera/video feed in real time
#     suc, frame = cam.read()
#     frame = cv2.resize(frame,(200,200),fx=0,fy=0, interpolation = cv2.INTER_CUBIC)
#     #frame = cv2.resize(image, (480, 360))
#     #plt.imshow(frame)
#     #frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    
#     #operation like 'imshow' on image
#     cv2.imshow('image', frame)
#     if cv2.waitKey(1) & 0xFF == ord('q'):
#         break
    
    
#     if curr_time - last_recorded_time >= 0.5:# it has been at least 5 seconds
#         count+=1
# #        frame = arr[0].numpy().astype("uint8")
#         Y = image.img_to_array(frame)
#         X = tf.expand_dims(Y,axis=0)
#         val = model.predict(X)
#         print(val)        

# #        img = images[i].numpy().astype("uint8")
# #         img_array = tf.keras.utils.img_to_array(frame)
# #         img_array = tf.expand_dims(img_array, 0) # Create a batch
# #         predictions = model.predict(img_array)
# #        score = tf.nn.softmax(predictions[0])


# #         score = tf.nn.softmax(val[0])
# #         x = class_names[np.argmax(score)]
# #         print(predictions)
# #         if predictions[0][1] > 0.5:
# #             cv2.imwrite(os.path.join('D:\Y\Accident-No' , F"{count}.jpg"), frame)
# #         else:
# #             cv2.imwrite(os.path.join('D:\Y\Accident-Yes' , F"{count}.jpg" ), frame)
    
            
# #         ax = plt.subplot(5, 5, i+1)
# #         plt.imshow(images[i].numpy().astype("uint8"))
# #         plt.title([i])
# #         plt.axis("off")
        
        
#         if val[0][1] > 0.5:
#             #print("Non-Acc")
#         #if predictions[0][1] > 0.5:
#         #CHNAGE
#             cv2.imwrite(os.path.join('D:\Y\Accident-Yes' , F"{count}.jpg"), frame)
            
#         else:
#             cv2.imwrite(os.path.join('D:\Y\Accident-No' , F"{count}.jpg" ), frame)
#             #cv2.waitKey(5000)
#             #break
             
#         #frame = frame.reshape(-1, 200, 200 ,3)
#         #print (frame.shape)
#         #frame = cv2.resize(frame,(200,200))
#         #plt.imshow(img)
#         #Y = image.img_to_array(frame)
            
#         #PROCESS YOUR IMAGE VARIABLE, img
#         #cv2.imwrite(os.path.join(path , 'frame{:d}.jpg'.format(count) ), frame)
#         #IMPORTANT CODE BELOW
#         last_recorded_time = curr_time
        
# cam.release()
# cv2.destroyAllWindows()

1/1 [==============================] - 0s 95ms/step
[[0.58752024 0.41247982]]
1/1 [==============================] - 0s 64ms/step
[[0.6205969 0.3794031]]
1/1 [==============================] - 0s 103ms/step
[[0.91749537 0.0825046 ]]
1/1 [==============================] - 0s 89ms/step
[[0.56700313 0.43299693]]
1/1 [==============================] - 0s 89ms/step
[[0.67618865 0.3238113 ]]
1/1 [==============================] - 0s 68ms/step
[[0.02031656 0.97968346]]
1/1 [==============================] - 0s 57ms/step
[[0.00860553 0.99139446]]
1/1 [==============================] - 0s 61ms/step
[[0.01682911 0.9831709 ]]
1/1 [==============================] - 0s 61ms/step
[[0.2532322  0.74676776]]
1/1 [==============================] - 0s 54ms/step
[[0.95796114 0.04203882]]
1/1 [==============================] - 0s 57ms/step
[[0.8390534  0.16094664]]
1/1 [==============================] - 0s 57ms/step
[[0.02206355 0.97793645]]
1/1 [==============================] - 0s 54ms/step
[[0.9362777 0

<Figure size 1500x1500 with 0 Axes>

In [14]:
cam.release()